# fly.toml app configuration file generated for delicate-bush-8558 on 2023-08-15T22:34:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delicate-bush-8558"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build.args]
  GO_VERSION = "1.22.0"

#[deploy]
#  release_command = "go run ./cmd/pgmigrate" does not work currently as it's using a dsn connection string in prod and migrate supports only the url

[experimental]
  auto_rollback = true

[deploy]
  strategy = "bluegreen"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 3333

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
