# fly.toml file generated for delicate-bush-8558 on 2021-06-16T19:20:02-05:00

app = "delicate-bush-8558"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

#[deploy]
#  release_command = "go run ./cmd/pgmigrate" does not work currently as it's using a dsn connection string in prod and migrate supports only the url

[env]
  PORT = "8080"
  STORAGE_PATH = "/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3333
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

[mounts]
  source = "data"
  destination = "/data"